 System.out.println(u);
			 */
		   
		   
			/*

machali jal ki rani h...
machali jal ki rani h...
machali jal ki rani h...
machali jal ki rani h...
machali jal ki rani h...
machali jal ki rani h...
machali jal ki rani h...
machali jal ki rani h...
machali jal ki rani h...
machali jal ki rani h...

			